  organizer_details:
    walletseed_phase: enlist already power frequent broken wait special diet copy will vendor clever
    password: ac041880
    confirm_password: ac041880
    key_private: 96b9f6decf4e52a23b5b3f50094c75f301d2ed055f9cef66f16c59d4f4be84fd

  participant_details:
    walletseed_phase: over shell actual bean minute fragile box response conduct nest fiscal bone
    password: cc041880
    confirm_password: cc041880
    key_private: 766bcf0349d8485a8725d87ee17ce885565c708ee7a7ef9d3e45698f5292bc23
    #tstnet_key_private: 766bcf0349d8485a8725d87ee17ce885565c708ee7a7ef9d3e45698f5292bc23
